Networking Project/Models/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace Networking_Project.Models
{
    public class User
    {
        [Key, Column(Order = 1)]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int idUser { get; set; }
        [Required]
        [StringLength(50, MinimumLength = 2)]
        public string FirstName { get; set; }
        [Required]
        [StringLength(50, MinimumLength = 2)]
        public string LastName { get; set; }
        [Required]
        [RegularExpression(@"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}",ErrorMessage ="Email should be like this format : X@X.XX")]
        public string Email { get; set; }

        [Required]
        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,15}$",ErrorMessage ="Password should be from 8 to 15 and contains at least one upper and lower case lettes asd one digit")]

        public string Password { get; set; }

        [NotMapped]
        [Required]
        [System.ComponentModel.DataAnnotations.Compare("Password")]
        public string ConfirmPassword { get; set; }
        public string FullName()
        {
            return this.FirstName + " " + this.LastName;
        }
    }
}

Networking Project/Controllers/TicketController.cs
using Networking_Project.Dal;
using Networking_Project.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Networking_Project.Controllers
{
    public class TicketController : Controller
    {
        // GET: Ticket
        public ActionResult seats(int id)
        {
            using (MovieDal m = new MovieDal())
            {

                return View(m.Movies.ToList<Movie>().Where(x => x.mid == id).FirstOrDefault());
            }
        }

        [HttpPost]
        public ActionResult seats(int id, Movie m , int seat = -1)
        {
            MovieDal mdb = new MovieDal();
            Movie m1 = mdb.Movies.ToList<Movie>().Where(x => x.mid == id).FirstOrDefault();

            //out of range seats
            HallDal hd = new HallDal();
            Hall h = hd.Halls.ToList<Hall>().Where(x => x.HallNumber == m1.Hall).FirstOrDefault();
            if(h.number_of_seats < seat || seat < 1)
            {
                ViewBag.check = "Out of range seat! , please choose a seat from 1 to "+h.number_of_seats.ToString();
                return View(m1);
            }


            //check if the seat is in occupied
            TicketDal tdb = new TicketDal();
            List<Ticket> t = tdb.Tickets.ToList<Ticket>();
            int count = 0;
            foreach(Ticket t1 in t)
            {
                if (t1.Seat == seat && t1.Hall == m1.Hall && t1.Date.Equals(m1.Date))
                    count++;
            }
            //create ticket
            if(count == 0)
            {

                Ticket tt = new Ticket();
                tt.Hall = m1.Hall;
                if (m1.Sale == null)
                    tt.Price = m1.Price;
                else
                    tt.Price = (int)m1.Sale;
                tt.Id = m1.mid;
                tt.Movietitle = m1.Title;
                tt.Date = m1.Date;
                tt.Seat = seat;
                tt.Userid = (int)Session["idUser"];
                tdb.Tickets.Add(tt);
                tdb.SaveChanges();
                ViewBag.check = "added to cart succefully !";
                //add rating to most popular
                MostDal ms = new MostDal();
                Most most = ms.Mosts.ToList<Most>().Where(x => x.Title == m1.Title).FirstOrDefault();
                most.rate += 1;
                ms.Entry(most).State = EntityState.Modified;
                ms.SaveChanges();
            }
            else
                ViewBag.check = "this seat in occupied !";
            return View(m1);
        }
        public ActionResult Cart()
        {
            if (Session["idUser"] == null)
            {
                Random rnd = new Random();
                int id = rnd.Next(1000);
                Session["idUser"] = id;
            }

            using (TicketDal mdb = new TicketDal())
            {
                int d = (int)Session["idUser"];
                return View(mdb.Tickets.ToList<Ticket>().Where(x => x.Userid == d));
            }
        }


        public ActionResult Delete(int id)
        {
            using (TicketDal mdb = new TicketDal())
            {
                return View(mdb.Tickets.Where(x => x.Id == id).FirstOrDefault());
            }
        }
        [HttpPost]
        public ActionResult Delete(int id, Ticket c)
        {
            try
            {
                using (TicketDal mdb = new TicketDal())
                {
                    Ticket m = mdb.Tickets.Where(x => x.Id == id).FirstOrDefault();
                    mdb.Tickets.Remove(m);
                    mdb.SaveChanges();
                    return RedirectToAction("Cart");
                }
            }
            catch
            {
                return View();
            }
        }

    }
}

Networking Project/Controllers/UserController.cs
using System;
using System.Text;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Networking_Project.Models;
using System.Security.Cryptography;
using Networking_Project.VM;
using Networking_Project.Dal;
using System.Data.Entity;
using System.Globalization;

namespace Networking_Project.Controllers
{
    public class UserController : Controller
    {
        private DB_Entities _db = new DB_Entities();
        // GET: Home
        public ActionResult Index()
        {
            //removing ended movies and tickets
            using (MovieDal mdb = new MovieDal())
            {
                foreach (Movie movie in mdb.Movies.ToList<Movie>())
                {
                    int res = DateTime.Compare(movie.Date, DateTime.Now);
                    if (res < 0)
                    {

                        mdb.Movies.Remove(movie);
                        mdb.SaveChanges();
                        TicketDal tdb = new TicketDal();
                        foreach (Ticket t in tdb.Tickets.ToList<Ticket>())
                        {
                            if (t.Movietitle == movie.Title && t.Hall == movie.Hall && DateTime.Compare(movie.Date, t.Date) == 0)
                            {
                                tdb.Tickets.Remove(t);
                                tdb.SaveChanges();
                            }
                        }
                    }
                }
            }

            //creating id for user
            if (Session["idUser"] == null)
            {
                Random rnd = new Random();
                int id = rnd.Next(1000);
                Session["idUser"] = id;
            }
            using (MovieDal mdb = new MovieDal())
            {
                return View("Home", mdb.Movies.ToList<Movie>().Where(x => x.Sale == null));
            }

        }
        //sorting movies

        public ActionResult Index99(int from,int to,bool Decrease=false, bool Increase = false)
        {
            MovieDal mdb = new MovieDal();
            List<Movie> lm = new List<Movie>();

            string[] formats = {"DD/MM/yyyy"};

            //price range
            foreach (Movie x in mdb.Movies.ToList<Movie>().Where(m => m.Sale == null && m.Price > from && m.Price < to))
            {
                ViewBag.range = "from " + from.ToString() + " to " + to.ToString();
                //both catefory and date
                if (Request.Form["Select Category"] != null && Request.Form["Select Category"].ToString() != "All" && DateTime.TryParse(Request.Form["date1"], out DateTime date1) == true)
                {
                    ViewBag.category = Request.Form["Select Category"].ToString();
                    ViewBag.date5 = date1.ToString();
                    if (x.Category == Request.Form["Select Category"].ToString() && x.Date.Year == date1.Year && x.Date.Month == date1.Month && x.Date.Day == date1.Day)
                    {
                        lm.Add(x);
                    }
                }

                //sort by category alone
                else if (Request.Form["Select Category"] != null && Request.Form["Select Category"].ToString() != "All")
                {
                    ViewBag.category = Request.Form["Select Category"].ToString();
                    if (Request.Form["Select Category"].ToString() != "All")
                    {
                        if (x.Category == Request.Form["Select Category"].ToString())
                        {
                            lm.Add(x);
                        }
                    }
                }
                //sort date alone
                else if (DateTime.TryParse(Request.Form["date1"], out DateTime date11) == true)
                {
                    if(x.Date.Year == date11.Year && x.Date.Month == date11.Month && x.Date.Day == date11.Day)
                    {
                        ViewBag.date5 = date11.ToString();
                        lm.Add(x);
                    }
                }

                else
                    lm.Add(x);
            }
            //price decrease .. increase
            if (Decrease)
                lm = lm.OrderBy(q => q.Price).Reverse().ToList();
            if (Increase)
                lm = lm.OrderBy(q => q.Price).ToList();
            return View("Home",lm);
        }

        //movie details

        public ActionResult Details(int id)
        {
            using (MovieDal mdb = new MovieDal())
            {
                return View( mdb.Movies.Where(x => x.mid==id).FirstOrDefault());
            }
        }
        //edit movie
        public ActionResult Edit(int id)
        {
            using (MovieDal mdb = new MovieDal())
            {
                return View(mdb.Movies.Where(x => x.mid == id).FirstOrDefault());
            }
        }
        [HttpPost]
        public ActionResult Edit(int id , Movie c)
        {
            try
            {
                using (MovieDal mdb = new MovieDal())
                {
                    c.Picture = "~/UploadedFiles/" + c.Picture.ToString();
                    mdb.Entry(c).State = EntityState.Modified;
                    mdb.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        //sales
        public ActionResult PutOnSale(int id)
        {
            using (MovieDal mdb = new MovieDal())
            {
                return View(mdb.Movies.Where(x => x.mid == id).FirstOrDefault());
            }
        }
        [HttpPost]
        public ActionResult PutOnSale(int id,int sale)
        {
            try
            {
                using (MovieDal mdb = new MovieDal())
                {
                    Movie c = mdb.Movies.Where(x => x.mid == id).FirstOrDefault();
                    c.Sale = sale;
                    mdb.Entry(c).State = EntityState.Modified;
                    mdb.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Sales()
        {
            if (Session["idUser"] == null)
            {
                Random rnd = new Random();
                int id = rnd.Next(1000);
                Session["idUser"] = id;

            }
            using (MovieDal mdb = new MovieDal())
            {
                return View(mdb.Movies.ToList<Movie>().Where(x=>x.Sale != null));
            }
        }

        //delete movie
        public ActionResult Delete(int id)
        {
            using (MovieDal mdb = new MovieDal())
            {
                return View(mdb.Movies.Where(x => x.mid == id).FirstOrDefault());
            }
        }
        [HttpPost]
        public ActionResult Delete(int id,Movie c)
        {
            try
            {
                using (MovieDal mdb = new MovieDal())
                {
                    Movie m = mdb.Movies.Where(x => x.mid == id).FirstOrDefault();
                    mdb.Movies.Remove(m);
                    mdb.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch
            {
                return View();
            }
        }
        // home screen
        public ActionResult Home()
        {
            if(Session["idUser"] == null)
            {
                Random rnd = new Random();
                int id = rnd.Next(1000);
                Session["idUser"] = id;

            }
            using (MovieDal mdb = new MovieDal())
            {
                return View(mdb.Movies.ToList<Movie>().Where(x => x.Sale == null));
            }
        }
        //most popular
        public ActionResult Mostpopular()
        {
            MostDal mostdb = new MostDal();
            MovieDal mdb = new MovieDal();
            List<Movie> lm = new List<Movie>();
            foreach (Most most in mostdb.Mosts.ToList<Most>().OrderBy(x => x.rate).Reverse())
            {
                foreach (Movie movie in mdb.Movies.ToList<Movie>())
                {
                    if (movie.Title == most.Title && movie.Sale == null)
                        lm.Add(movie);
                }
            }
            return View("Home",lm);
        }






        //user login signup
        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(User _user)
        {
            if (ModelState.IsValid)
            {
                var check = _db.Users.FirstOrDefault(s => s.Email == _user.Email);
                if (check == null)
                {
                    _user.Password = GetMD5(_user.Password);
                    _db.Configuration.ValidateOnSaveEnabled = false;
                    _db.Users.Add(_user);
                    _db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.error = "Email already exists";
                    return View();
                }


            }
            return View();


        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(string email, string password)
        {
            if (ModelState.IsValid)
            {


                var f_password = GetMD5(password);
                var data = _db.Users.Where(s => s.Email.Equals(email) && s.Password.Equals(f_password)).ToList();
                if (data.Count() > 0)
                {
                    //add session
                    Session["FullName"] = data.FirstOrDefault().FirstName + " " + data.FirstOrDefault().LastName;

Networking Project/Views/User/Delete.cshtml
@model Networking_Project.Models.Movie

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Movie</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hall)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hall)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Picture)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Picture)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Networking Project/Views/User/Details.cshtml
@model Networking_Project.Models.Movie

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body >
    <div>
        <h4>Movie</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Title)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Title)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Date)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Date)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Price)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Price)₪
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Hall)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Hall)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Category)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Category)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Picture)
            </dt>

            <dd>
                <img src="@Url.Content(Model.Picture)" width="500" height="300" multiple />
            </dd>


        </dl>
    </div>
    <p>
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

Networking Project/Views/User/Home.cshtml
@model IEnumerable<Networking_Project.Models.Movie>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    //Session["Email"] = "admin";
}
@using Networking_Project.Models;
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>home</title>
</head>
<body>

    <br />
    @Html.ActionLink("Most popular", "Mostpopular", "user")
    <br />
    @using (Html.BeginForm("Index99", "User", FormMethod.Post))
    {
        <span>Sort by : </span> @Html.DropDownList("Select Category", new SelectList(Enum.GetValues(typeof(Categoty))), new { htmlAttributes = new { @class = "form-control" } }) <a style="color:crimson">@ViewBag.category</a>
        <br />
        <span>Search by DATE:</span> <input type="date" name="date1" /> <a style="color:crimson">@ViewBag.date5</a>
        <br />
        <span>Price range from </span> <input type="number" name="from" value=0 /> <span> to </span> <input type="number" name="to" value=400 /> <a style="color:crimson">@ViewBag.range</a>
        <br />
        @Html.CheckBox("Decrease") <span>From highest to lowest price</span>
        <br />
        @Html.CheckBox("Increase") <span>From lowest to highest price</span>
        <br />
        <input type="submit" value="Filter" />
    }







    <br />
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                Price ₪
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Picture)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)₪
                </td>
                <td>
                    <img src="@Url.Content(item.Picture)" width="250" height="150" multiple />
                </td>
                @if (Session["Email"] != null && Session["Email"].ToString() == "admin")
                {
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.mid }) |
                        @Html.ActionLink("Details", "Details", new { id = item.mid }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.mid }) |
                        @Html.ActionLink("Put on sale", "PutOnSale", new { id = item.mid })
                    </td>
                }
                else
                {
                    <td>
                        @Html.ActionLink("Details", "Details", new { id = item.mid }) |
                        @Html.ActionLink("Pick a seat", "seats", "Ticket", new { id = item.mid }, null)
                    </td>
                }
            </tr>
        }

    </table>
</body>
</html>

Networking Project/Views/User/Login.cshtml
@model Networking_Project.Models.User

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>
    <link href="~/styles/style.css" rel="stylesheet" />
</head>
<body>
    <div>
        <div class="row justify-content-md-center">
            <div class="col-md-4">
                <div class="card">
                    <div class="card-header">
                        <br />
                        <h3>Login</h3>
                    </div>
                    <div class="card-body">
                        <br />
                        @using (Html.BeginForm("Login", "User", FormMethod.Post))
                        {
                            @Html.AntiForgeryToken()
                            <div class="form-group">
                                @Html.LabelFor(m => m.Email)
                                @Html.TextBoxFor(m => m.Email, "", new { @class = "form-control", @placeholder = "Email" })

                            </div>
                            <div class="form-group">
                                @Html.LabelFor(m => m.Password)
                                @Html.PasswordFor(m => m.Password, new { @class = "form-control", @placeholder = "Password" })
                            </div>
                            <div class="form-group">
                                <input type="submit" name="submit" class="btn btn-primary" value="Login" />
                            </div>
                        }
                    <div>Don't have an account ?@Html.ActionLink("Sign up", "Register", "User")</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

Networking Project/Views/User/PutOnSale.cshtml
@model Networking_Project.Models.Movie

@{
    ViewBag.Title = "PutOnSale";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>PutOnSale</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Movie</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.mid)

        <div class="form-group">
            @Html.Label("Inter Sale Price :", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="number" name="sale" value=@Model.Price />
                @Html.ValidationMessageFor(model => model.Sale, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Movie ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.mid, new { disabled = "true" })
                @Html.ValidationMessageFor(model => model.mid, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Networking Project/Views/User/Register.cshtml
@model Networking_Project.Models.User



@{
    ViewBag.Title = "Register";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Register</title>
</head>
<body>
    <div class="row justify-content-md-center">
        <div class="col-md-5">
            @using (Html.BeginForm("Register", "User", FormMethod.Post))
            {
                //@Html.ValidationSummary()
                @Html.AntiForgeryToken()

                <div class="card">
                    <div class="card-header">
                        <br />
                        <div class="card-title">Register</div>
                        <br />
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            @Html.LabelFor(m => m.FirstName)
                            @Html.TextBoxFor(m => m.FirstName, "", new { @class = "form-control", @placeholder = "First Name" })
                            @Html.ValidationMessageFor(m => m.FirstName, "", new { @class = "badge badge-danger" })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(m => m.LastName)
                            @Html.TextBoxFor(m => m.LastName, "", new { @class = "form-control", @placeholder = "Last Name" })
                            @Html.ValidationMessageFor(m => m.LastName, "", new { @class = "badge badge-danger" })

                        </div>
                        <div class="form-group">
                            @Html.LabelFor(m => m.Email)
                            @Html.TextBoxFor(m => m.Email, "", new { @class = "form-control", @placeholder = "Email" })
                            @Html.ValidationMessageFor(m => m.Email, "", new { @class = "badge badge-danger" })
                            @if (ViewBag.error != null)
                            {
                                <span class="badge badge-danger">@ViewBag.error</span>
                            }
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(m => m.Password)
                            @Html.PasswordFor(m => m.Password, new { @class = "form-control", @placeholder = "Password" })
                            @Html.ValidationMessageFor(m => m.Password, "", new { @class = "badge badge-danger" })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(m => m.ConfirmPassword)
                            @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control", @placeholder = "Confim Password" })
                            @Html.ValidationMessageFor(m => m.ConfirmPassword, "", new { @class = "badge badge-danger" })
                        </div>
                        <div class="form-group">
                            <input type="submit" name="submit" class="btn btn-danger" value="Register" />
                        </div>
                    </div>
                </div>

            }
        </div>
    </div>
</body>
</html>

Networking Project/Views/User/Sales.cshtml
@model IEnumerable<Networking_Project.Models.Movie>

@{
    ViewBag.Title = "Sales";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Sales</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Hall)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Picture)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Category)
        </th>
        <th>
            <a>Buy</a>
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Title)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Date)
    </td>
    <td>
        <del>@Html.DisplayFor(modelItem => item.Price)₪</del> <a> </a> @Html.DisplayFor(modelItem => item.Sale)₪
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Hall)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Description)
    </td>
    <td>
        <img src="@Url.Content(item.Picture)" width="250" height="150" multiple />
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Category)
    </td>
    <td>
        @Html.ActionLink("Pick a seat", "seats", "Ticket", new { id = item.mid }, null)
    </td>
</tr>
}

</table>